// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceAuthReq.proto

package com.taoyiyi.chat.proto;

public final class DeviceAuthReq {
  private DeviceAuthReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceAuthReqMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.DeviceAuthReqMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     * @return The enum numeric value on the wire for authType.
     */
    int getAuthTypeValue();
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     * @return The authType.
     */
    com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType();

    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     * @return The credential.
     */
    java.lang.String getCredential();
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     * @return The bytes for credential.
     */
    com.google.protobuf.ByteString
        getCredentialBytes();

    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string Version = 3;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string Version = 3;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *客户端版本
     * </pre>
     *
     * <code>string clientVersion = 4;</code>
     * @return The clientVersion.
     */
    java.lang.String getClientVersion();
    /**
     * <pre>
     *客户端版本
     * </pre>
     *
     * <code>string clientVersion = 4;</code>
     * @return The bytes for clientVersion.
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *租户ID
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The tenantId.
     */
    java.lang.String getTenantId();
    /**
     * <pre>
     *租户ID
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The bytes for tenantId.
     */
    com.google.protobuf.ByteString
        getTenantIdBytes();

    /**
     * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
     * @return The enum numeric value on the wire for userRole.
     */
    int getUserRoleValue();
    /**
     * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
     * @return The userRole.
     */
    com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole getUserRole();
  }
  /**
   * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthReqMessage}
   */
  public static final class DeviceAuthReqMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.DeviceAuthReqMessage)
      DeviceAuthReqMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceAuthReqMessage.newBuilder() to construct.
    private DeviceAuthReqMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceAuthReqMessage() {
      authType_ = 0;
      credential_ = "";
      version_ = "";
      clientVersion_ = "";
      ip_ = "";
      tenantId_ = "";
      userRole_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceAuthReqMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceAuthReqMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              authType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              credential_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              clientVersion_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              tenantId_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              userRole_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.DeviceAuthReq.internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoyiyi.chat.proto.DeviceAuthReq.internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.class, com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.Builder.class);
    }

    /**
     * <pre>
     *认证方式枚举
     * </pre>
     *
     * Protobuf enum {@code com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType}
     */
    public enum EnumAuthType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *默认方式，默认使用
       * </pre>
       *
       * <code>Default = 0;</code>
       */
      Default(0),
      /**
       * <pre>
       *设备码（用于手机客户端，此方式Credential应传入手机IMEI）
       * </pre>
       *
       * <code>DeviceCode = 1;</code>
       */
      DeviceCode(1),
      /**
       * <pre>
       *用户名密码方式（此方式Credential应传入base64(user:pwd)）
       * </pre>
       *
       * <code>Username = 2;</code>
       */
      Username(2),
      /**
       * <pre>
       *内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）
       * </pre>
       *
       * <code>InternalCode = 3;</code>
       */
      InternalCode(3),
      /**
       * <pre>
       * 用户编码
       * </pre>
       *
       * <code>UserCode = 4;</code>
       */
      UserCode(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *默认方式，默认使用
       * </pre>
       *
       * <code>Default = 0;</code>
       */
      public static final int Default_VALUE = 0;
      /**
       * <pre>
       *设备码（用于手机客户端，此方式Credential应传入手机IMEI）
       * </pre>
       *
       * <code>DeviceCode = 1;</code>
       */
      public static final int DeviceCode_VALUE = 1;
      /**
       * <pre>
       *用户名密码方式（此方式Credential应传入base64(user:pwd)）
       * </pre>
       *
       * <code>Username = 2;</code>
       */
      public static final int Username_VALUE = 2;
      /**
       * <pre>
       *内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）
       * </pre>
       *
       * <code>InternalCode = 3;</code>
       */
      public static final int InternalCode_VALUE = 3;
      /**
       * <pre>
       * 用户编码
       * </pre>
       *
       * <code>UserCode = 4;</code>
       */
      public static final int UserCode_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EnumAuthType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EnumAuthType forNumber(int value) {
        switch (value) {
          case 0: return Default;
          case 1: return DeviceCode;
          case 2: return Username;
          case 3: return InternalCode;
          case 4: return UserCode;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnumAuthType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EnumAuthType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnumAuthType>() {
              public EnumAuthType findValueByNumber(int number) {
                return EnumAuthType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnumAuthType[] VALUES = values();

      public static EnumAuthType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EnumAuthType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType)
    }

    public static final int AUTHTYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     * @return The enum numeric value on the wire for authType.
     */
    @java.lang.Override public int getAuthTypeValue() {
      return authType_;
    }
    /**
     * <pre>
     *认证方式
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
     * @return The authType.
     */
    @java.lang.Override public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType() {
      @SuppressWarnings("deprecation")
      com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType result = com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.valueOf(authType_);
      return result == null ? com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.UNRECOGNIZED : result;
    }

    public static final int CREDENTIAL_FIELD_NUMBER = 2;
    private volatile java.lang.Object credential_;
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     * @return The credential.
     */
    @java.lang.Override
    public java.lang.String getCredential() {
      java.lang.Object ref = credential_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credential_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *凭证信息（不同认证方式传入不同的凭证信息）
     * </pre>
     *
     * <code>string Credential = 2;</code>
     * @return The bytes for credential.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCredentialBytes() {
      java.lang.Object ref = credential_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object version_;
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string Version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string Version = 3;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object clientVersion_;
    /**
     * <pre>
     *客户端版本
     * </pre>
     *
     * <code>string clientVersion = 4;</code>
     * @return The clientVersion.
     */
    @java.lang.Override
    public java.lang.String getClientVersion() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端版本
     * </pre>
     *
     * <code>string clientVersion = 4;</code>
     * @return The bytes for clientVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object ip_;
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANTID_FIELD_NUMBER = 6;
    private volatile java.lang.Object tenantId_;
    /**
     * <pre>
     *租户ID
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *租户ID
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERROLE_FIELD_NUMBER = 7;
    private int userRole_;
    /**
     * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
     * @return The enum numeric value on the wire for userRole.
     */
    @java.lang.Override public int getUserRoleValue() {
      return userRole_;
    }
    /**
     * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
     * @return The userRole.
     */
    @java.lang.Override public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole getUserRole() {
      @SuppressWarnings("deprecation")
      com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.valueOf(userRole_);
      return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (authType_ != com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.Default.getNumber()) {
        output.writeEnum(1, authType_);
      }
      if (!getCredentialBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, credential_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientVersion_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ip_);
      }
      if (!getTenantIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tenantId_);
      }
      if (userRole_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.merchant.getNumber()) {
        output.writeEnum(7, userRole_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (authType_ != com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.Default.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (!getCredentialBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, credential_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientVersion_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ip_);
      }
      if (!getTenantIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tenantId_);
      }
      if (userRole_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.merchant.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, userRole_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage)) {
        return super.equals(obj);
      }
      com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage other = (com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage) obj;

      if (authType_ != other.authType_) return false;
      if (!getCredential()
          .equals(other.getCredential())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getClientVersion()
          .equals(other.getClientVersion())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
      if (userRole_ != other.userRole_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHTYPE_FIELD_NUMBER;
      hash = (53 * hash) + authType_;
      hash = (37 * hash) + CREDENTIAL_FIELD_NUMBER;
      hash = (53 * hash) + getCredential().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + CLIENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + TENANTID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
      hash = (37 * hash) + USERROLE_FIELD_NUMBER;
      hash = (53 * hash) + userRole_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoyiyi.chat.proto.DeviceAuthReqMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.DeviceAuthReqMessage)
        com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoyiyi.chat.proto.DeviceAuthReq.internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoyiyi.chat.proto.DeviceAuthReq.internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.class, com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.Builder.class);
      }

      // Construct using com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authType_ = 0;

        credential_ = "";

        version_ = "";

        clientVersion_ = "";

        ip_ = "";

        tenantId_ = "";

        userRole_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoyiyi.chat.proto.DeviceAuthReq.internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstanceForType() {
        return com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage build() {
        com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage buildPartial() {
        com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage result = new com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage(this);
        result.authType_ = authType_;
        result.credential_ = credential_;
        result.version_ = version_;
        result.clientVersion_ = clientVersion_;
        result.ip_ = ip_;
        result.tenantId_ = tenantId_;
        result.userRole_ = userRole_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage) {
          return mergeFrom((com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage other) {
        if (other == com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.getDefaultInstance()) return this;
        if (other.authType_ != 0) {
          setAuthTypeValue(other.getAuthTypeValue());
        }
        if (!other.getCredential().isEmpty()) {
          credential_ = other.credential_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getClientVersion().isEmpty()) {
          clientVersion_ = other.clientVersion_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getTenantId().isEmpty()) {
          tenantId_ = other.tenantId_;
          onChanged();
        }
        if (other.userRole_ != 0) {
          setUserRoleValue(other.getUserRoleValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int authType_ = 0;
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       * @return The enum numeric value on the wire for authType.
       */
      @java.lang.Override public int getAuthTypeValue() {
        return authType_;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       * @param value The enum numeric value on the wire for authType to set.
       * @return This builder for chaining.
       */
      public Builder setAuthTypeValue(int value) {
        
        authType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       * @return The authType.
       */
      @java.lang.Override
      public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType getAuthType() {
        @SuppressWarnings("deprecation")
        com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType result = com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.valueOf(authType_);
        return result == null ? com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       * @param value The authType to set.
       * @return This builder for chaining.
       */
      public Builder setAuthType(com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage.EnumAuthType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *认证方式
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.DeviceAuthReqMessage.EnumAuthType AuthType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthType() {
        
        authType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object credential_ = "";
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       * @return The credential.
       */
      public java.lang.String getCredential() {
        java.lang.Object ref = credential_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          credential_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       * @return The bytes for credential.
       */
      public com.google.protobuf.ByteString
          getCredentialBytes() {
        java.lang.Object ref = credential_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          credential_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       * @param value The credential to set.
       * @return This builder for chaining.
       */
      public Builder setCredential(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        credential_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCredential() {
        
        credential_ = getDefaultInstance().getCredential();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *凭证信息（不同认证方式传入不同的凭证信息）
       * </pre>
       *
       * <code>string Credential = 2;</code>
       * @param value The bytes for credential to set.
       * @return This builder for chaining.
       */
      public Builder setCredentialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        credential_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       *版本
       * </pre>
       *
       * <code>string Version = 3;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *版本
       * </pre>
       *
       * <code>string Version = 3;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *版本
       * </pre>
       *
       * <code>string Version = 3;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本
       * </pre>
       *
       * <code>string Version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本
       * </pre>
       *
       * <code>string Version = 3;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientVersion_ = "";
      /**
       * <pre>
       *客户端版本
       * </pre>
       *
       * <code>string clientVersion = 4;</code>
       * @return The clientVersion.
       */
      public java.lang.String getClientVersion() {
        java.lang.Object ref = clientVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端版本
       * </pre>
       *
       * <code>string clientVersion = 4;</code>
       * @return The bytes for clientVersion.
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        java.lang.Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端版本
       * </pre>
       *
       * <code>string clientVersion = 4;</code>
       * @param value The clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端版本
       * </pre>
       *
       * <code>string clientVersion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = getDefaultInstance().getClientVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端版本
       * </pre>
       *
       * <code>string clientVersion = 4;</code>
       * @param value The bytes for clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <pre>
       *客户端ip
       * </pre>
       *
       * <code>string ip = 5;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端ip
       * </pre>
       *
       * <code>string ip = 5;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端ip
       * </pre>
       *
       * <code>string ip = 5;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ip
       * </pre>
       *
       * <code>string ip = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ip
       * </pre>
       *
       * <code>string ip = 5;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tenantId_ = "";
      /**
       * <pre>
       *租户ID
       * </pre>
       *
       * <code>string tenantId = 6;</code>
       * @return The tenantId.
       */
      public java.lang.String getTenantId() {
        java.lang.Object ref = tenantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tenantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *租户ID
       * </pre>
       *
       * <code>string tenantId = 6;</code>
       * @return The bytes for tenantId.
       */
      public com.google.protobuf.ByteString
          getTenantIdBytes() {
        java.lang.Object ref = tenantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *租户ID
       * </pre>
       *
       * <code>string tenantId = 6;</code>
       * @param value The tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tenantId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *租户ID
       * </pre>
       *
       * <code>string tenantId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantId() {
        
        tenantId_ = getDefaultInstance().getTenantId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *租户ID
       * </pre>
       *
       * <code>string tenantId = 6;</code>
       * @param value The bytes for tenantId to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tenantId_ = value;
        onChanged();
        return this;
      }

      private int userRole_ = 0;
      /**
       * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
       * @return The enum numeric value on the wire for userRole.
       */
      @java.lang.Override public int getUserRoleValue() {
        return userRole_;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
       * @param value The enum numeric value on the wire for userRole to set.
       * @return This builder for chaining.
       */
      public Builder setUserRoleValue(int value) {
        
        userRole_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
       * @return The userRole.
       */
      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole getUserRole() {
        @SuppressWarnings("deprecation")
        com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.valueOf(userRole_);
        return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
       * @param value The userRole to set.
       * @return This builder for chaining.
       */
      public Builder setUserRole(com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumUserRole value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        userRole_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.taoyiyi.chat.proto.EnumUserRole userRole = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserRole() {
        
        userRole_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.DeviceAuthReqMessage)
    }

    // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.DeviceAuthReqMessage)
    private static final com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage();
    }

    public static com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceAuthReqMessage>
        PARSER = new com.google.protobuf.AbstractParser<DeviceAuthReqMessage>() {
      @java.lang.Override
      public DeviceAuthReqMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceAuthReqMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceAuthReqMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceAuthReqMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taoyiyi.chat.proto.DeviceAuthReq.DeviceAuthReqMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DeviceAuthReq.proto\022\026com.taoyiyi.chat." +
      "proto\032\026TransportMessage.proto\"\320\002\n\024Device" +
      "AuthReqMessage\022K\n\010AuthType\030\001 \001(\01629.com.t" +
      "aoyiyi.chat.proto.DeviceAuthReqMessage.E" +
      "numAuthType\022\022\n\nCredential\030\002 \001(\t\022\017\n\007Versi" +
      "on\030\003 \001(\t\022\025\n\rclientVersion\030\004 \001(\t\022\n\n\002ip\030\005 " +
      "\001(\t\022\020\n\010tenantId\030\006 \001(\t\0226\n\010userRole\030\007 \001(\0162" +
      "$.com.taoyiyi.chat.proto.EnumUserRole\"Y\n" +
      "\014EnumAuthType\022\013\n\007Default\020\000\022\016\n\nDeviceCode" +
      "\020\001\022\014\n\010Username\020\002\022\020\n\014InternalCode\020\003\022\014\n\010Us" +
      "erCode\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor(),
        });
    internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_DeviceAuthReqMessage_descriptor,
        new java.lang.String[] { "AuthType", "Credential", "Version", "ClientVersion", "Ip", "TenantId", "UserRole", });
    com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
