// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TalkToOther.proto

package com.taoyiyi.chat.proto;

public final class TalkToOther {
  private TalkToOther() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TalkToOtherMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.TalkToOtherMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送人
     * </pre>
     *
     * <code>string formUser = 1;</code>
     * @return The formUser.
     */
    java.lang.String getFormUser();
    /**
     * <pre>
     * 发送人
     * </pre>
     *
     * <code>string formUser = 1;</code>
     * @return The bytes for formUser.
     */
    com.google.protobuf.ByteString
        getFormUserBytes();

    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string toUser = 2;</code>
     * @return The toUser.
     */
    java.lang.String getToUser();
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string toUser = 2;</code>
     * @return The bytes for toUser.
     */
    com.google.protobuf.ByteString
        getToUserBytes();

    /**
     * <pre>
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
     * @return The enum numeric value on the wire for contentType.
     */
    int getContentTypeValue();
    /**
     * <pre>
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
     * @return The contentType.
     */
    com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType getContentType();

    /**
     * <pre>
     * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     * </pre>
     *
     * <code>string remark = 8;</code>
     * @return The remark.
     */
    java.lang.String getRemark();
    /**
     * <pre>
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     * </pre>
     *
     * <code>string remark = 8;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <pre>
     * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     * </pre>
     *
     * <code>int64 msgId = 9;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code com.taoyiyi.chat.proto.TalkToOtherMessage}
   */
  public static final class TalkToOtherMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.TalkToOtherMessage)
      TalkToOtherMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TalkToOtherMessage.newBuilder() to construct.
    private TalkToOtherMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TalkToOtherMessage() {
      formUser_ = "";
      toUser_ = "";
      contentType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      remark_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TalkToOtherMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TalkToOtherMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              formUser_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              toUser_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              contentType_ = rawValue;
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            case 72: {

              msgId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TalkToOther.internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoyiyi.chat.proto.TalkToOther.internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.class, com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.Builder.class);
    }

    public static final int FORMUSER_FIELD_NUMBER = 1;
    private volatile java.lang.Object formUser_;
    /**
     * <pre>
     * 发送人
     * </pre>
     *
     * <code>string formUser = 1;</code>
     * @return The formUser.
     */
    @java.lang.Override
    public java.lang.String getFormUser() {
      java.lang.Object ref = formUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人
     * </pre>
     *
     * <code>string formUser = 1;</code>
     * @return The bytes for formUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormUserBytes() {
      java.lang.Object ref = formUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUSER_FIELD_NUMBER = 2;
    private volatile java.lang.Object toUser_;
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string toUser = 2;</code>
     * @return The toUser.
     */
    @java.lang.Override
    public java.lang.String getToUser() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string toUser = 2;</code>
     * @return The bytes for toUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToUserBytes() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 3;
    private int contentType_;
    /**
     * <pre>
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
     * @return The enum numeric value on the wire for contentType.
     */
    @java.lang.Override public int getContentTypeValue() {
      return contentType_;
    }
    /**
     * <pre>
     * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
     * @return The contentType.
     */
    @java.lang.Override public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType getContentType() {
      @SuppressWarnings("deprecation")
      com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.valueOf(contentType_);
      return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
     * </pre>
     *
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int REMARK_FIELD_NUMBER = 8;
    private volatile java.lang.Object remark_;
    /**
     * <pre>
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     * </pre>
     *
     * <code>string remark = 8;</code>
     * @return The remark.
     */
    @java.lang.Override
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
     * </pre>
     *
     * <code>string remark = 8;</code>
     * @return The bytes for remark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 9;
    private long msgId_;
    /**
     * <pre>
     * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
     * </pre>
     *
     * <code>int64 msgId = 9;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFormUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, formUser_);
      }
      if (!getToUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toUser_);
      }
      if (contentType_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.UnknownContent.getNumber()) {
        output.writeEnum(3, contentType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, remark_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(9, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFormUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, formUser_);
      }
      if (!getToUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toUser_);
      }
      if (contentType_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.UnknownContent.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, contentType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, remark_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage)) {
        return super.equals(obj);
      }
      com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage other = (com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage) obj;

      if (!getFormUser()
          .equals(other.getFormUser())) return false;
      if (!getToUser()
          .equals(other.getToUser())) return false;
      if (contentType_ != other.contentType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORMUSER_FIELD_NUMBER;
      hash = (53 * hash) + getFormUser().hashCode();
      hash = (37 * hash) + TOUSER_FIELD_NUMBER;
      hash = (53 * hash) + getToUser().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + contentType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoyiyi.chat.proto.TalkToOtherMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.TalkToOtherMessage)
        com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoyiyi.chat.proto.TalkToOther.internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoyiyi.chat.proto.TalkToOther.internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.class, com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.Builder.class);
      }

      // Construct using com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        formUser_ = "";

        toUser_ = "";

        contentType_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        remark_ = "";

        msgId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoyiyi.chat.proto.TalkToOther.internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage getDefaultInstanceForType() {
        return com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage build() {
        com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage buildPartial() {
        com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage result = new com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage(this);
        result.formUser_ = formUser_;
        result.toUser_ = toUser_;
        result.contentType_ = contentType_;
        result.content_ = content_;
        result.remark_ = remark_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage) {
          return mergeFrom((com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage other) {
        if (other == com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage.getDefaultInstance()) return this;
        if (!other.getFormUser().isEmpty()) {
          formUser_ = other.formUser_;
          onChanged();
        }
        if (!other.getToUser().isEmpty()) {
          toUser_ = other.toUser_;
          onChanged();
        }
        if (other.contentType_ != 0) {
          setContentTypeValue(other.getContentTypeValue());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object formUser_ = "";
      /**
       * <pre>
       * 发送人
       * </pre>
       *
       * <code>string formUser = 1;</code>
       * @return The formUser.
       */
      public java.lang.String getFormUser() {
        java.lang.Object ref = formUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          formUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送人
       * </pre>
       *
       * <code>string formUser = 1;</code>
       * @return The bytes for formUser.
       */
      public com.google.protobuf.ByteString
          getFormUserBytes() {
        java.lang.Object ref = formUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          formUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人
       * </pre>
       *
       * <code>string formUser = 1;</code>
       * @param value The formUser to set.
       * @return This builder for chaining.
       */
      public Builder setFormUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        formUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人
       * </pre>
       *
       * <code>string formUser = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormUser() {
        
        formUser_ = getDefaultInstance().getFormUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人
       * </pre>
       *
       * <code>string formUser = 1;</code>
       * @param value The bytes for formUser to set.
       * @return This builder for chaining.
       */
      public Builder setFormUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        formUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toUser_ = "";
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string toUser = 2;</code>
       * @return The toUser.
       */
      public java.lang.String getToUser() {
        java.lang.Object ref = toUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string toUser = 2;</code>
       * @return The bytes for toUser.
       */
      public com.google.protobuf.ByteString
          getToUserBytes() {
        java.lang.Object ref = toUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string toUser = 2;</code>
       * @param value The toUser to set.
       * @return This builder for chaining.
       */
      public Builder setToUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string toUser = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUser() {
        
        toUser_ = getDefaultInstance().getToUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string toUser = 2;</code>
       * @param value The bytes for toUser to set.
       * @return This builder for chaining.
       */
      public Builder setToUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUser_ = value;
        onChanged();
        return this;
      }

      private int contentType_ = 0;
      /**
       * <pre>
       * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
       * @return The enum numeric value on the wire for contentType.
       */
      @java.lang.Override public int getContentTypeValue() {
        return contentType_;
      }
      /**
       * <pre>
       * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
       * @param value The enum numeric value on the wire for contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentTypeValue(int value) {
        
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
       * @return The contentType.
       */
      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType getContentType() {
        @SuppressWarnings("deprecation")
        com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.valueOf(contentType_);
        return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
       * @param value The contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentType(com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumContentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        contentType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送消息类型 Text Picture Voice Video Link File NameCard WeApp Quote Emoji ShiPinHao
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumContentType contentType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentType() {
        
        contentType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送消息内容 文本; 图片，视频，语音，文件url; 链接json; 名片wxid; Emoji的md5或Emoji的详细json
       * </pre>
       *
       * <code>bytes content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <pre>
       * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
       * </pre>
       *
       * <code>string remark = 8;</code>
       * @return The remark.
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
       * </pre>
       *
       * <code>string remark = 8;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
       * </pre>
       *
       * <code>string remark = 8;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
       * </pre>
       *
       * <code>string remark = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他备注信息，群聊&#64;别人；Quote（引用消息）：引用消息的msgSvrId字符串
       * </pre>
       *
       * <code>string remark = 8;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
       * </pre>
       *
       * <code>int64 msgId = 9;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
       * </pre>
       *
       * <code>int64 msgId = 9;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送给手机端的时候需要赋值，用于TalkToFriendTaskResultNotice中
       * </pre>
       *
       * <code>int64 msgId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.TalkToOtherMessage)
    }

    // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.TalkToOtherMessage)
    private static final com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage();
    }

    public static com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TalkToOtherMessage>
        PARSER = new com.google.protobuf.AbstractParser<TalkToOtherMessage>() {
      @java.lang.Override
      public TalkToOtherMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TalkToOtherMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TalkToOtherMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TalkToOtherMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taoyiyi.chat.proto.TalkToOther.TalkToOtherMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TalkToOther.proto\022\026com.taoyiyi.chat.pr" +
      "oto\032\026TransportMessage.proto\"\244\001\n\022TalkToOt" +
      "herMessage\022\020\n\010formUser\030\001 \001(\t\022\016\n\006toUser\030\002" +
      " \001(\t\022<\n\013contentType\030\003 \001(\0162\'.com.taoyiyi." +
      "chat.proto.EnumContentType\022\017\n\007content\030\004 " +
      "\001(\014\022\016\n\006remark\030\010 \001(\t\022\r\n\005msgId\030\t \001(\003b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor(),
        });
    internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_TalkToOtherMessage_descriptor,
        new java.lang.String[] { "FormUser", "ToUser", "ContentType", "Content", "Remark", "MsgId", });
    com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
