// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportMessage.proto

package com.taoyiyi.chat.proto;

public final class TransportMessageOuterClass {
  private TransportMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息类型枚举，一般每一个消息类型都应该对应一个特定的message结构
   *20xx形式的消息类型需要 手机客户端开发者留意
   *30xx形式的消息类型需要 PC客户端开发者留意
   *10xx形式的消息类型需要 手机客户端、PC客户端开发者留意
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumMsgType}
   */
  public enum EnumMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知消息
     * </pre>
     *
     * <code>UnknownMsg = 0;</code>
     */
    UnknownMsg(0),
    /**
     * <pre>
     *客户端发送的心跳包
     * </pre>
     *
     * <code>HeartBeatReq = 1001;</code>
     */
    HeartBeatReq(1001),
    /**
     * <pre>
     *消息接收确认回复（接收或拒绝接收）
     * </pre>
     *
     * <code>MsgReceivedAck = 1002;</code>
     */
    MsgReceivedAck(1002),
    /**
     * <pre>
     * 将错误单独提升为一种消息类型 4.1
     * </pre>
     *
     * <code>Error = 1003;</code>
     */
    Error(1003),
    /**
     * <pre>
     * 设备客户端授权类消息
     * </pre>
     *
     * <code>DeviceAuthReq = 1010;</code>
     */
    DeviceAuthReq(1010),
    /**
     * <pre>
     *设备(手机客户端、客服客户端)获取通信token响应 4.3
     * </pre>
     *
     * <code>DeviceAuthRsp = 1011;</code>
     */
    DeviceAuthRsp(1011),
    /**
     * <pre>
     *设备授权后退出(仅用于服务端内部)
     * </pre>
     *
     * <code>DeviceExitNotice = 1012;</code>
     */
    DeviceExitNotice(1012),
    /**
     * <pre>
     *账号强制下线通知 4.18
     * </pre>
     *
     * <code>AccountForceOfflineNotice = 1013;</code>
     */
    AccountForceOfflineNotice(1013),
    /**
     * <code>RedirectNotice = 1015;</code>
     */
    RedirectNotice(1015),
    /**
     * <code>TriggerDeviceInfo = 1016;</code>
     */
    TriggerDeviceInfo(1016),
    /**
     * <pre>
     * 发送消息
     * </pre>
     *
     * <code>TalkToOther = 1070;</code>
     */
    TalkToOther(1070),
    /**
     * <pre>
     * 手机客户端上传的通知类消息
     * </pre>
     *
     * <code>TriggerChatPushTask = 1019;</code>
     */
    TriggerChatPushTask(1019),
    /**
     * <pre>
     *手机客户端上线通知 4.4
     * </pre>
     *
     * <code>OnlineNotice = 1020;</code>
     */
    OnlineNotice(1020),
    /**
     * <pre>
     *手机客户端下线通知 4.5
     * </pre>
     *
     * <code>OfflineNotice = 1021;</code>
     */
    OfflineNotice(1021),
    /**
     * <pre>
     * 客户端上传日志 4.202
     * </pre>
     *
     * <code>PostLogReq = 3202;</code>
     */
    PostLogReq(3202),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未知消息
     * </pre>
     *
     * <code>UnknownMsg = 0;</code>
     */
    public static final int UnknownMsg_VALUE = 0;
    /**
     * <pre>
     *客户端发送的心跳包
     * </pre>
     *
     * <code>HeartBeatReq = 1001;</code>
     */
    public static final int HeartBeatReq_VALUE = 1001;
    /**
     * <pre>
     *消息接收确认回复（接收或拒绝接收）
     * </pre>
     *
     * <code>MsgReceivedAck = 1002;</code>
     */
    public static final int MsgReceivedAck_VALUE = 1002;
    /**
     * <pre>
     * 将错误单独提升为一种消息类型 4.1
     * </pre>
     *
     * <code>Error = 1003;</code>
     */
    public static final int Error_VALUE = 1003;
    /**
     * <pre>
     * 设备客户端授权类消息
     * </pre>
     *
     * <code>DeviceAuthReq = 1010;</code>
     */
    public static final int DeviceAuthReq_VALUE = 1010;
    /**
     * <pre>
     *设备(手机客户端、客服客户端)获取通信token响应 4.3
     * </pre>
     *
     * <code>DeviceAuthRsp = 1011;</code>
     */
    public static final int DeviceAuthRsp_VALUE = 1011;
    /**
     * <pre>
     *设备授权后退出(仅用于服务端内部)
     * </pre>
     *
     * <code>DeviceExitNotice = 1012;</code>
     */
    public static final int DeviceExitNotice_VALUE = 1012;
    /**
     * <pre>
     *账号强制下线通知 4.18
     * </pre>
     *
     * <code>AccountForceOfflineNotice = 1013;</code>
     */
    public static final int AccountForceOfflineNotice_VALUE = 1013;
    /**
     * <code>RedirectNotice = 1015;</code>
     */
    public static final int RedirectNotice_VALUE = 1015;
    /**
     * <code>TriggerDeviceInfo = 1016;</code>
     */
    public static final int TriggerDeviceInfo_VALUE = 1016;
    /**
     * <pre>
     * 发送消息
     * </pre>
     *
     * <code>TalkToOther = 1070;</code>
     */
    public static final int TalkToOther_VALUE = 1070;
    /**
     * <pre>
     * 手机客户端上传的通知类消息
     * </pre>
     *
     * <code>TriggerChatPushTask = 1019;</code>
     */
    public static final int TriggerChatPushTask_VALUE = 1019;
    /**
     * <pre>
     *手机客户端上线通知 4.4
     * </pre>
     *
     * <code>OnlineNotice = 1020;</code>
     */
    public static final int OnlineNotice_VALUE = 1020;
    /**
     * <pre>
     *手机客户端下线通知 4.5
     * </pre>
     *
     * <code>OfflineNotice = 1021;</code>
     */
    public static final int OfflineNotice_VALUE = 1021;
    /**
     * <pre>
     * 客户端上传日志 4.202
     * </pre>
     *
     * <code>PostLogReq = 3202;</code>
     */
    public static final int PostLogReq_VALUE = 3202;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumMsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumMsgType forNumber(int value) {
      switch (value) {
        case 0: return UnknownMsg;
        case 1001: return HeartBeatReq;
        case 1002: return MsgReceivedAck;
        case 1003: return Error;
        case 1010: return DeviceAuthReq;
        case 1011: return DeviceAuthRsp;
        case 1012: return DeviceExitNotice;
        case 1013: return AccountForceOfflineNotice;
        case 1015: return RedirectNotice;
        case 1016: return TriggerDeviceInfo;
        case 1070: return TalkToOther;
        case 1019: return TriggerChatPushTask;
        case 1020: return OnlineNotice;
        case 1021: return OfflineNotice;
        case 3202: return PostLogReq;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumMsgType>() {
            public EnumMsgType findValueByNumber(int number) {
              return EnumMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumMsgType[] VALUES = values();

    public static EnumMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumMsgType)
  }

  /**
   * <pre>
   * 全局错误码表
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumErrorCode}
   */
  public enum EnumErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *无错误
     * </pre>
     *
     * <code>Success = 0;</code>
     */
    Success(0),
    /**
     * <pre>
     *无权限
     * </pre>
     *
     * <code>NoRight = 1001;</code>
     */
    NoRight(1001),
    /**
     * <pre>
     *数据信息不合法
     * </pre>
     *
     * <code>InvalidParam = 1002;</code>
     */
    InvalidParam(1002),
    /**
     * <pre>
     *内部处理错误
     * </pre>
     *
     * <code>InternalError = 1003;</code>
     */
    InternalError(1003),
    /**
     * <pre>
     *发送消息或指令时对方不在线
     * </pre>
     *
     * <code>TargetNotOnline = 1004;</code>
     */
    TargetNotOnline(1004),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *无错误
     * </pre>
     *
     * <code>Success = 0;</code>
     */
    public static final int Success_VALUE = 0;
    /**
     * <pre>
     *无权限
     * </pre>
     *
     * <code>NoRight = 1001;</code>
     */
    public static final int NoRight_VALUE = 1001;
    /**
     * <pre>
     *数据信息不合法
     * </pre>
     *
     * <code>InvalidParam = 1002;</code>
     */
    public static final int InvalidParam_VALUE = 1002;
    /**
     * <pre>
     *内部处理错误
     * </pre>
     *
     * <code>InternalError = 1003;</code>
     */
    public static final int InternalError_VALUE = 1003;
    /**
     * <pre>
     *发送消息或指令时对方不在线
     * </pre>
     *
     * <code>TargetNotOnline = 1004;</code>
     */
    public static final int TargetNotOnline_VALUE = 1004;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumErrorCode forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1001: return NoRight;
        case 1002: return InvalidParam;
        case 1003: return InternalError;
        case 1004: return TargetNotOnline;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumErrorCode>() {
            public EnumErrorCode findValueByNumber(int number) {
              return EnumErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final EnumErrorCode[] VALUES = values();

    public static EnumErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumErrorCode)
  }

  /**
   * <pre>
   * 性别枚举
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumGender}
   */
  public enum EnumGender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>UnknownGender = 0;</code>
     */
    UnknownGender(0),
    /**
     * <pre>
     *男
     * </pre>
     *
     * <code>Male = 1;</code>
     */
    Male(1),
    /**
     * <pre>
     *女
     * </pre>
     *
     * <code>Female = 2;</code>
     */
    Female(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>UnknownGender = 0;</code>
     */
    public static final int UnknownGender_VALUE = 0;
    /**
     * <pre>
     *男
     * </pre>
     *
     * <code>Male = 1;</code>
     */
    public static final int Male_VALUE = 1;
    /**
     * <pre>
     *女
     * </pre>
     *
     * <code>Female = 2;</code>
     */
    public static final int Female_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumGender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumGender forNumber(int value) {
      switch (value) {
        case 0: return UnknownGender;
        case 1: return Male;
        case 2: return Female;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumGender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumGender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumGender>() {
            public EnumGender findValueByNumber(int number) {
              return EnumGender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(2);
    }

    private static final EnumGender[] VALUES = values();

    public static EnumGender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumGender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumGender)
  }

  /**
   * <pre>
   * 聊天内容类型
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumContentType}
   */
  public enum EnumContentType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知内容
     * </pre>
     *
     * <code>UnknownContent = 0;</code>
     */
    UnknownContent(0),
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>Text = 1;</code>
     */
    Text(1),
    /**
     * <pre>
     * 图片消息
     * </pre>
     *
     * <code>Picture = 2;</code>
     */
    Picture(2),
    /**
     * <pre>
     * 语音消息
     * </pre>
     *
     * <code>Voice = 3;</code>
     */
    Voice(3),
    /**
     * <pre>
     * 视频消息
     * </pre>
     *
     * <code>Video = 4;</code>
     */
    Video(4),
    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>System = 5;</code>
     */
    System(5),
    /**
     * <pre>
     * 链接消息
     * </pre>
     *
     * <code>Link = 6;</code>
     */
    Link(6),
    /**
     * <pre>
     * 扩展的链接消息
     * </pre>
     *
     * <code>LinkExt = 7;</code>
     */
    LinkExt(7),
    /**
     * <pre>
     * 文件发送
     * </pre>
     *
     * <code>File = 8;</code>
     */
    File(8),
    /**
     * <pre>
     * 名片
     * </pre>
     *
     * <code>NameCard = 9;</code>
     */
    NameCard(9),
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>Location = 10;</code>
     */
    Location(10),
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>Emoji = 14;</code>
     */
    Emoji(14),
    /**
     * <pre>
     * 语音通话
     * </pre>
     *
     * <code>AudioCall = 19;</code>
     */
    AudioCall(19),
    /**
     * <pre>
     * 视频通话
     * </pre>
     *
     * <code>VideoCall = 20;</code>
     */
    VideoCall(20),
    /**
     * <pre>
     * 服务通知
     * </pre>
     *
     * <code>NotifyMsg = 21;</code>
     */
    NotifyMsg(21),
    /**
     * <pre>
     * 引用通知
     * </pre>
     *
     * <code>QuoteMsg = 22;</code>
     */
    QuoteMsg(22),
    /**
     * <pre>
     * 聊天记录
     * </pre>
     *
     * <code>ChatRecord = 31;</code>
     */
    ChatRecord(31),
    /**
     * <pre>
     * 不支持的消息
     * </pre>
     *
     * <code>UnSupport = 99;</code>
     */
    UnSupport(99),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知内容
     * </pre>
     *
     * <code>UnknownContent = 0;</code>
     */
    public static final int UnknownContent_VALUE = 0;
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>Text = 1;</code>
     */
    public static final int Text_VALUE = 1;
    /**
     * <pre>
     * 图片消息
     * </pre>
     *
     * <code>Picture = 2;</code>
     */
    public static final int Picture_VALUE = 2;
    /**
     * <pre>
     * 语音消息
     * </pre>
     *
     * <code>Voice = 3;</code>
     */
    public static final int Voice_VALUE = 3;
    /**
     * <pre>
     * 视频消息
     * </pre>
     *
     * <code>Video = 4;</code>
     */
    public static final int Video_VALUE = 4;
    /**
     * <pre>
     *系统消息
     * </pre>
     *
     * <code>System = 5;</code>
     */
    public static final int System_VALUE = 5;
    /**
     * <pre>
     * 链接消息
     * </pre>
     *
     * <code>Link = 6;</code>
     */
    public static final int Link_VALUE = 6;
    /**
     * <pre>
     * 扩展的链接消息
     * </pre>
     *
     * <code>LinkExt = 7;</code>
     */
    public static final int LinkExt_VALUE = 7;
    /**
     * <pre>
     * 文件发送
     * </pre>
     *
     * <code>File = 8;</code>
     */
    public static final int File_VALUE = 8;
    /**
     * <pre>
     * 名片
     * </pre>
     *
     * <code>NameCard = 9;</code>
     */
    public static final int NameCard_VALUE = 9;
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>Location = 10;</code>
     */
    public static final int Location_VALUE = 10;
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>Emoji = 14;</code>
     */
    public static final int Emoji_VALUE = 14;
    /**
     * <pre>
     * 语音通话
     * </pre>
     *
     * <code>AudioCall = 19;</code>
     */
    public static final int AudioCall_VALUE = 19;
    /**
     * <pre>
     * 视频通话
     * </pre>
     *
     * <code>VideoCall = 20;</code>
     */
    public static final int VideoCall_VALUE = 20;
    /**
     * <pre>
     * 服务通知
     * </pre>
     *
     * <code>NotifyMsg = 21;</code>
     */
    public static final int NotifyMsg_VALUE = 21;
    /**
     * <pre>
     * 引用通知
     * </pre>
     *
     * <code>QuoteMsg = 22;</code>
     */
    public static final int QuoteMsg_VALUE = 22;
    /**
     * <pre>
     * 聊天记录
     * </pre>
     *
     * <code>ChatRecord = 31;</code>
     */
    public static final int ChatRecord_VALUE = 31;
    /**
     * <pre>
     * 不支持的消息
     * </pre>
     *
     * <code>UnSupport = 99;</code>
     */
    public static final int UnSupport_VALUE = 99;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumContentType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumContentType forNumber(int value) {
      switch (value) {
        case 0: return UnknownContent;
        case 1: return Text;
        case 2: return Picture;
        case 3: return Voice;
        case 4: return Video;
        case 5: return System;
        case 6: return Link;
        case 7: return LinkExt;
        case 8: return File;
        case 9: return NameCard;
        case 10: return Location;
        case 14: return Emoji;
        case 19: return AudioCall;
        case 20: return VideoCall;
        case 21: return NotifyMsg;
        case 22: return QuoteMsg;
        case 31: return ChatRecord;
        case 99: return UnSupport;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumContentType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumContentType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumContentType>() {
            public EnumContentType findValueByNumber(int number) {
              return EnumContentType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(3);
    }

    private static final EnumContentType[] VALUES = values();

    public static EnumContentType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumContentType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumContentType)
  }

  /**
   * <pre>
   * 设备 ~ 号 在线状态枚举
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumOnlineState}
   */
  public enum EnumOnlineState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知，在条件中可认为是全部
     * </pre>
     *
     * <code>UnknownState = 0;</code>
     */
    UnknownState(0),
    /**
     * <pre>
     * 在线
     * </pre>
     *
     * <code>Online = 1;</code>
     */
    Online(1),
    /**
     * <pre>
     * 离线
     * </pre>
     *
     * <code>Offline = 2;</code>
     */
    Offline(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知，在条件中可认为是全部
     * </pre>
     *
     * <code>UnknownState = 0;</code>
     */
    public static final int UnknownState_VALUE = 0;
    /**
     * <pre>
     * 在线
     * </pre>
     *
     * <code>Online = 1;</code>
     */
    public static final int Online_VALUE = 1;
    /**
     * <pre>
     * 离线
     * </pre>
     *
     * <code>Offline = 2;</code>
     */
    public static final int Offline_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumOnlineState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumOnlineState forNumber(int value) {
      switch (value) {
        case 0: return UnknownState;
        case 1: return Online;
        case 2: return Offline;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumOnlineState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumOnlineState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumOnlineState>() {
            public EnumOnlineState findValueByNumber(int number) {
              return EnumOnlineState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(4);
    }

    private static final EnumOnlineState[] VALUES = values();

    public static EnumOnlineState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumOnlineState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumOnlineState)
  }

  /**
   * <pre>
   * 任务类型
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumTaskType}
   */
  public enum EnumTaskType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知，不应该出现，但是协议需要
     * </pre>
     *
     * <code>UnknownTask = 0;</code>
     */
    UnknownTask(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知，不应该出现，但是协议需要
     * </pre>
     *
     * <code>UnknownTask = 0;</code>
     */
    public static final int UnknownTask_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumTaskType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumTaskType forNumber(int value) {
      switch (value) {
        case 0: return UnknownTask;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumTaskType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumTaskType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumTaskType>() {
            public EnumTaskType findValueByNumber(int number) {
              return EnumTaskType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(5);
    }

    private static final EnumTaskType[] VALUES = values();

    public static EnumTaskType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumTaskType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumTaskType)
  }

  /**
   * <pre>
   * 消息发送状态
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumSendStatus}
   */
  public enum EnumSendStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 无状态
     * </pre>
     *
     * <code>NoAction = 0;</code>
     */
    NoAction(0),
    /**
     * <pre>
     * 发送中
     * </pre>
     *
     * <code>Sending = 1;</code>
     */
    Sending(1),
    /**
     * <pre>
     * 发送成功
     * </pre>
     *
     * <code>SendSuccess = 17;</code>
     */
    SendSuccess(17),
    /**
     * <pre>
     * 发送失败
     * </pre>
     *
     * <code>SendError = 16;</code>
     */
    SendError(16),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 无状态
     * </pre>
     *
     * <code>NoAction = 0;</code>
     */
    public static final int NoAction_VALUE = 0;
    /**
     * <pre>
     * 发送中
     * </pre>
     *
     * <code>Sending = 1;</code>
     */
    public static final int Sending_VALUE = 1;
    /**
     * <pre>
     * 发送成功
     * </pre>
     *
     * <code>SendSuccess = 17;</code>
     */
    public static final int SendSuccess_VALUE = 17;
    /**
     * <pre>
     * 发送失败
     * </pre>
     *
     * <code>SendError = 16;</code>
     */
    public static final int SendError_VALUE = 16;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumSendStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumSendStatus forNumber(int value) {
      switch (value) {
        case 0: return NoAction;
        case 1: return Sending;
        case 17: return SendSuccess;
        case 16: return SendError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumSendStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumSendStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumSendStatus>() {
            public EnumSendStatus findValueByNumber(int number) {
              return EnumSendStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(6);
    }

    private static final EnumSendStatus[] VALUES = values();

    public static EnumSendStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumSendStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumSendStatus)
  }

  /**
   * <pre>
   * 被强制下线的原因
   * </pre>
   *
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumForceOfflineReason}
   */
  public enum EnumForceOfflineReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 就是要下线你 
     * </pre>
     *
     * <code>NoReason = 0;</code>
     */
    NoReason(0),
    /**
     * <pre>
     * 别处登录挤下线了 
     * </pre>
     *
     * <code>FuckedByOtherAuthorizer = 1;</code>
     */
    FuckedByOtherAuthorizer(1),
    /**
     * <pre>
     * 被重新分配
     * </pre>
     *
     * <code>ByReAlloc = 2;</code>
     */
    ByReAlloc(2),
    /**
     * <pre>
     * 设备下线而下线
     * </pre>
     *
     * <code>ByDeviceOffline = 3;</code>
     */
    ByDeviceOffline(3),
    /**
     * <pre>
     * 主动下线
     * </pre>
     *
     * <code>ByOffline = 4;</code>
     */
    ByOffline(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 就是要下线你 
     * </pre>
     *
     * <code>NoReason = 0;</code>
     */
    public static final int NoReason_VALUE = 0;
    /**
     * <pre>
     * 别处登录挤下线了 
     * </pre>
     *
     * <code>FuckedByOtherAuthorizer = 1;</code>
     */
    public static final int FuckedByOtherAuthorizer_VALUE = 1;
    /**
     * <pre>
     * 被重新分配
     * </pre>
     *
     * <code>ByReAlloc = 2;</code>
     */
    public static final int ByReAlloc_VALUE = 2;
    /**
     * <pre>
     * 设备下线而下线
     * </pre>
     *
     * <code>ByDeviceOffline = 3;</code>
     */
    public static final int ByDeviceOffline_VALUE = 3;
    /**
     * <pre>
     * 主动下线
     * </pre>
     *
     * <code>ByOffline = 4;</code>
     */
    public static final int ByOffline_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumForceOfflineReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumForceOfflineReason forNumber(int value) {
      switch (value) {
        case 0: return NoReason;
        case 1: return FuckedByOtherAuthorizer;
        case 2: return ByReAlloc;
        case 3: return ByDeviceOffline;
        case 4: return ByOffline;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumForceOfflineReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumForceOfflineReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumForceOfflineReason>() {
            public EnumForceOfflineReason findValueByNumber(int number) {
              return EnumForceOfflineReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(7);
    }

    private static final EnumForceOfflineReason[] VALUES = values();

    public static EnumForceOfflineReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumForceOfflineReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumForceOfflineReason)
  }

  /**
   * Protobuf enum {@code com.taoyiyi.chat.proto.EnumUserRole}
   */
  public enum EnumUserRole
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 商家
     * </pre>
     *
     * <code>merchant = 0;</code>
     */
    merchant(0),
    /**
     * <pre>
     * 技师
     * </pre>
     *
     * <code>tech = 1;</code>
     */
    tech(1),
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>cus = 2;</code>
     */
    cus(2),
    /**
     * <pre>
     * 系统
     * </pre>
     *
     * <code>sys = 3;</code>
     */
    sys(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 商家
     * </pre>
     *
     * <code>merchant = 0;</code>
     */
    public static final int merchant_VALUE = 0;
    /**
     * <pre>
     * 技师
     * </pre>
     *
     * <code>tech = 1;</code>
     */
    public static final int tech_VALUE = 1;
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>cus = 2;</code>
     */
    public static final int cus_VALUE = 2;
    /**
     * <pre>
     * 系统
     * </pre>
     *
     * <code>sys = 3;</code>
     */
    public static final int sys_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumUserRole valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumUserRole forNumber(int value) {
      switch (value) {
        case 0: return merchant;
        case 1: return tech;
        case 2: return cus;
        case 3: return sys;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumUserRole>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumUserRole> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumUserRole>() {
            public EnumUserRole findValueByNumber(int number) {
              return EnumUserRole.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.getDescriptor().getEnumTypes().get(8);
    }

    private static final EnumUserRole[] VALUES = values();

    public static EnumUserRole valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumUserRole(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.taoyiyi.chat.proto.EnumUserRole)
  }

  public interface TransportMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.taoyiyi.chat.proto.TransportMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息Id(发送方内保持自增),请求中传入，响应中传回相同值
     * </pre>
     *
     * <code>int64 Id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *设备通信token
     * </pre>
     *
     * <code>string AccessToken = 2;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <pre>
     *设备通信token
     * </pre>
     *
     * <code>string AccessToken = 2;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <pre>
     *承载的具体消息类型
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *承载的具体消息类型
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
     * @return The msgType.
     */
    com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType getMsgType();

    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     * @return The content.
     */
    com.google.protobuf.Any getContent();
    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getContentOrBuilder();

    /**
     * <pre>
     *如果是针对某个消息的响应，这里写对应请求的id
     * </pre>
     *
     * <code>int64 RefMessageId = 5;</code>
     * @return The refMessageId.
     */
    long getRefMessageId();
  }
  /**
   * <pre>
   *根传输消息
   * </pre>
   *
   * Protobuf type {@code com.taoyiyi.chat.proto.TransportMessage}
   */
  public static final class TransportMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.taoyiyi.chat.proto.TransportMessage)
      TransportMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportMessage.newBuilder() to construct.
    private TransportMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportMessage() {
      accessToken_ = "";
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransportMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransportMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              refMessageId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoyiyi.chat.proto.TransportMessageOuterClass.internal_static_com_taoyiyi_chat_proto_TransportMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.class, com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *消息Id(发送方内保持自增),请求中传入，响应中传回相同值
     * </pre>
     *
     * <code>int64 Id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object accessToken_;
    /**
     * <pre>
     *设备通信token
     * </pre>
     *
     * <code>string AccessToken = 2;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *设备通信token
     * </pre>
     *
     * <code>string AccessToken = 2;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <pre>
     *承载的具体消息类型
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *承载的具体消息类型
     * </pre>
     *
     * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
     * @return The msgType.
     */
    @java.lang.Override public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.valueOf(msgType_);
      return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.Any content_;
    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.Any getContent() {
      return content_ == null ? com.google.protobuf.Any.getDefaultInstance() : content_;
    }
    /**
     * <pre>
     *具体的消息数据
     * </pre>
     *
     * <code>.google.protobuf.Any Content = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
      return getContent();
    }

    public static final int REFMESSAGEID_FIELD_NUMBER = 5;
    private long refMessageId_;
    /**
     * <pre>
     *如果是针对某个消息的响应，这里写对应请求的id
     * </pre>
     *
     * <code>int64 RefMessageId = 5;</code>
     * @return The refMessageId.
     */
    @java.lang.Override
    public long getRefMessageId() {
      return refMessageId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accessToken_);
      }
      if (msgType_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.UnknownMsg.getNumber()) {
        output.writeEnum(3, msgType_);
      }
      if (content_ != null) {
        output.writeMessage(4, getContent());
      }
      if (refMessageId_ != 0L) {
        output.writeInt64(5, refMessageId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accessToken_);
      }
      if (msgType_ != com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.UnknownMsg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, msgType_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getContent());
      }
      if (refMessageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, refMessageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage)) {
        return super.equals(obj);
      }
      com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage other = (com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (msgType_ != other.msgType_) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (getRefMessageId()
          != other.getRefMessageId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (37 * hash) + REFMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRefMessageId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *根传输消息
     * </pre>
     *
     * Protobuf type {@code com.taoyiyi.chat.proto.TransportMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.taoyiyi.chat.proto.TransportMessage)
        com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoyiyi.chat.proto.TransportMessageOuterClass.internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoyiyi.chat.proto.TransportMessageOuterClass.internal_static_com_taoyiyi_chat_proto_TransportMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.class, com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.Builder.class);
      }

      // Construct using com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        accessToken_ = "";

        msgType_ = 0;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        refMessageId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoyiyi.chat.proto.TransportMessageOuterClass.internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage getDefaultInstanceForType() {
        return com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage build() {
        com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage buildPartial() {
        com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage result = new com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage(this);
        result.id_ = id_;
        result.accessToken_ = accessToken_;
        result.msgType_ = msgType_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.refMessageId_ = refMessageId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage) {
          return mergeFrom((com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage other) {
        if (other == com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.getRefMessageId() != 0L) {
          setRefMessageId(other.getRefMessageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息Id(发送方内保持自增),请求中传入，响应中传回相同值
       * </pre>
       *
       * <code>int64 Id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息Id(发送方内保持自增),请求中传入，响应中传回相同值
       * </pre>
       *
       * <code>int64 Id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息Id(发送方内保持自增),请求中传入，响应中传回相同值
       * </pre>
       *
       * <code>int64 Id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <pre>
       *设备通信token
       * </pre>
       *
       * <code>string AccessToken = 2;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *设备通信token
       * </pre>
       *
       * <code>string AccessToken = 2;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *设备通信token
       * </pre>
       *
       * <code>string AccessToken = 2;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备通信token
       * </pre>
       *
       * <code>string AccessToken = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备通信token
       * </pre>
       *
       * <code>string AccessToken = 2;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *承载的具体消息类型
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *承载的具体消息类型
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *承载的具体消息类型
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType result = com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.valueOf(msgType_);
        return result == null ? com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *承载的具体消息类型
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(com.taoyiyi.chat.proto.TransportMessageOuterClass.EnumMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *承载的具体消息类型
       * </pre>
       *
       * <code>.com.taoyiyi.chat.proto.EnumMsgType MsgType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> contentBuilder_;
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       * @return The content.
       */
      public com.google.protobuf.Any getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? com.google.protobuf.Any.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.Any value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public Builder setContent(
          com.google.protobuf.Any.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public Builder mergeContent(com.google.protobuf.Any value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              com.google.protobuf.Any.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public com.google.protobuf.Any.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : content_;
        }
      }
      /**
       * <pre>
       *具体的消息数据
       * </pre>
       *
       * <code>.google.protobuf.Any Content = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private long refMessageId_ ;
      /**
       * <pre>
       *如果是针对某个消息的响应，这里写对应请求的id
       * </pre>
       *
       * <code>int64 RefMessageId = 5;</code>
       * @return The refMessageId.
       */
      @java.lang.Override
      public long getRefMessageId() {
        return refMessageId_;
      }
      /**
       * <pre>
       *如果是针对某个消息的响应，这里写对应请求的id
       * </pre>
       *
       * <code>int64 RefMessageId = 5;</code>
       * @param value The refMessageId to set.
       * @return This builder for chaining.
       */
      public Builder setRefMessageId(long value) {
        
        refMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果是针对某个消息的响应，这里写对应请求的id
       * </pre>
       *
       * <code>int64 RefMessageId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefMessageId() {
        
        refMessageId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.taoyiyi.chat.proto.TransportMessage)
    }

    // @@protoc_insertion_point(class_scope:com.taoyiyi.chat.proto.TransportMessage)
    private static final com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage();
    }

    public static com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportMessage>
        PARSER = new com.google.protobuf.AbstractParser<TransportMessage>() {
      @java.lang.Override
      public TransportMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransportMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransportMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.taoyiyi.chat.proto.TransportMessageOuterClass.TransportMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_taoyiyi_chat_proto_TransportMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TransportMessage.proto\022\026com.taoyiyi.ch" +
      "at.proto\032\031google/protobuf/any.proto\"\246\001\n\020" +
      "TransportMessage\022\n\n\002Id\030\001 \001(\003\022\023\n\013AccessTo" +
      "ken\030\002 \001(\t\0224\n\007MsgType\030\003 \001(\0162#.com.taoyiyi" +
      ".chat.proto.EnumMsgType\022%\n\007Content\030\004 \001(\013" +
      "2\024.google.protobuf.Any\022\024\n\014RefMessageId\030\005" +
      " \001(\003*\301\002\n\013EnumMsgType\022\016\n\nUnknownMsg\020\000\022\021\n\014" +
      "HeartBeatReq\020\351\007\022\023\n\016MsgReceivedAck\020\352\007\022\n\n\005" +
      "Error\020\353\007\022\022\n\rDeviceAuthReq\020\362\007\022\022\n\rDeviceAu" +
      "thRsp\020\363\007\022\025\n\020DeviceExitNotice\020\364\007\022\036\n\031Accou" +
      "ntForceOfflineNotice\020\365\007\022\023\n\016RedirectNotic" +
      "e\020\367\007\022\026\n\021TriggerDeviceInfo\020\370\007\022\020\n\013TalkToOt" +
      "her\020\256\010\022\030\n\023TriggerChatPushTask\020\373\007\022\021\n\014Onli" +
      "neNotice\020\374\007\022\022\n\rOfflineNotice\020\375\007\022\017\n\nPostL" +
      "ogReq\020\202\031*g\n\rEnumErrorCode\022\013\n\007Success\020\000\022\014" +
      "\n\007NoRight\020\351\007\022\021\n\014InvalidParam\020\352\007\022\022\n\rInter" +
      "nalError\020\353\007\022\024\n\017TargetNotOnline\020\354\007*5\n\nEnu" +
      "mGender\022\021\n\rUnknownGender\020\000\022\010\n\004Male\020\001\022\n\n\006" +
      "Female\020\002*\200\002\n\017EnumContentType\022\022\n\016UnknownC" +
      "ontent\020\000\022\010\n\004Text\020\001\022\013\n\007Picture\020\002\022\t\n\005Voice" +
      "\020\003\022\t\n\005Video\020\004\022\n\n\006System\020\005\022\010\n\004Link\020\006\022\013\n\007L" +
      "inkExt\020\007\022\010\n\004File\020\010\022\014\n\010NameCard\020\t\022\014\n\010Loca" +
      "tion\020\n\022\t\n\005Emoji\020\016\022\r\n\tAudioCall\020\023\022\r\n\tVide" +
      "oCall\020\024\022\r\n\tNotifyMsg\020\025\022\014\n\010QuoteMsg\020\026\022\016\n\n" +
      "ChatRecord\020\037\022\r\n\tUnSupport\020c*<\n\017EnumOnlin" +
      "eState\022\020\n\014UnknownState\020\000\022\n\n\006Online\020\001\022\013\n\007" +
      "Offline\020\002*\037\n\014EnumTaskType\022\017\n\013UnknownTask" +
      "\020\000*K\n\016EnumSendStatus\022\014\n\010NoAction\020\000\022\013\n\007Se" +
      "nding\020\001\022\017\n\013SendSuccess\020\021\022\r\n\tSendError\020\020*" +
      "v\n\026EnumForceOfflineReason\022\014\n\010NoReason\020\000\022" +
      "\033\n\027FuckedByOtherAuthorizer\020\001\022\r\n\tByReAllo" +
      "c\020\002\022\023\n\017ByDeviceOffline\020\003\022\r\n\tByOffline\020\004*" +
      "8\n\014EnumUserRole\022\014\n\010merchant\020\000\022\010\n\004tech\020\001\022" +
      "\007\n\003cus\020\002\022\007\n\003sys\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_taoyiyi_chat_proto_TransportMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_taoyiyi_chat_proto_TransportMessage_descriptor,
        new java.lang.String[] { "Id", "AccessToken", "MsgType", "Content", "RefMessageId", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
